### ISSUE TITLE
[Feature Request] Get favorite radio list

### ISSUE THREAD

**Issue by avjui** [rahims/SoCo#12]
First Thanks for this nice python class. It works very nice.
I am working on  on a web page which includes sonos.
Please can you implement a new feature. It would be nice to become a  list of the Favorite radio station.

**Comment by rahims** [comment]
Could you tell me a bit more about the favorite radio list and/or include a screenshot? I don't see it in the Sonos application.

**Comment by avjui** [comment]
After some search it looks like sonos let get the information from tunein.
I don´t know if it possible to  get the information for radio. Perhaps you can find the private key how sonos use then the class can attached the information by him self
![radio_favourites_crss](https://f.cloud.github.com/assets/1090640/113658/225a765c-6b6b-11e2-8f81-5aff983b06ca.jpg)
.

**Comment by avjui** [comment]
Here also some links.
https://sonos.custhelp.com/app/answers/detail/a_id/818/session/L2F2LzEvdGltZS8xMzU5NjExOTQ4L3NpZC9OUDdjOUZobA%3D%3D
and
https://sonos.custhelp.com/app/answers/detail/a_id/84/~/tunein-radio-and-sonos

**Comment by avjui** [comment]
Hmm

It seems that under http://ip:1400/status/radiolog we can found partnerid and id perhaps this helps
After some look I found the the current radio station can be found with 
http://opml.radiotime.com/Describe.ashx?c=nowplaying&id=${ID}&partnerId=Sonos&serial=${SERIAL}

mfg

**Comment by rahims** [comment]
Haven't written the code for it yet, but from investigation, you can get the list of favorite "Radio Stations" by sending an HTTP/1.1 POST request to http://[ip]:1400/MediaServer/ContentDirectory/Control with the following:

``` http
POST /MediaServer/ContentDirectory/Control HTTP/1.1
CONNECTION: close
ACCEPT-ENCODING: gzip
HOST: 192.168.1.80:1400
USER-AGENT: Linux UPnP/1.0 Sonos/19.4-59140 (MDCR_MacBookAir4,1)
CONTENT-LENGTH: 481
CONTENT-TYPE: text/xml; charset="utf-8"
SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
      <ObjectID>R:0/0</ObjectID>
      <BrowseFlag>BrowseDirectChildren</BrowseFlag>
      <Filter>dc:title,res,dc:creator,upnp:artist,upnp:album,upnp:albumArtURI</Filter>
      <StartingIndex>0</StartingIndex>
      <RequestedCount>100</RequestedCount>
      <SortCriteria/>
    </u:Browse>
  </s:Body>
</s:Envelope>
```

Similarly, you can get a list of the favorite "Radio Shows" by sending an HTTP/1.1 POST request to http://[ip]:1400/MediaServer/ContentDirectory/Control with the following:

``` http
POST /MediaServer/ContentDirectory/Control HTTP/1.1
CONNECTION: close
ACCEPT-ENCODING: gzip
HOST: 192.168.1.80:1400
USER-AGENT: Linux UPnP/1.0 Sonos/19.4-59140 (MDCR_MacBookAir4,1)
CONTENT-LENGTH: 481
CONTENT-TYPE: text/xml; charset="utf-8"
SOAPACTION: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
      <ObjectID>R:0/1</ObjectID>
      <BrowseFlag>BrowseDirectChildren</BrowseFlag>
      <Filter>dc:title,res,dc:creator,upnp:artist,upnp:album,upnp:albumArtURI</Filter>
      <StartingIndex>0</StartingIndex>
      <RequestedCount>100</RequestedCount>
      <SortCriteria/>
    </u:Browse>
  </s:Body>
</s:Envelope>
```

Notice that the only difference between the requests is the value for `ObjectID`, `<ObjectID>R:0/0</ObjectID>` for "Radio Stations" and `<ObjectID>R:0/1</ObjectID>` for "Radio Shows".

The requests will return something like the following:

``` http
HTTP/1.1 200 OK
CONTENT-LENGTH: 990
CONTENT-TYPE: text/xml; charset="utf-8"
EXT: 
SERVER: Linux UPnP/1.0 Sonos/19.4-60120 (ZPS3)
Connection: close

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
      <Result>&lt;DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"&gt;&lt;item id="R:0/0/0" parentID="R:0/0" restricted="false"&gt;&lt;dc:title&gt;105.9 | Power 106 (Hip Hop)&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;res protocolInfo="x-rincon-mp3radio:*:*:*"&gt;x-sonosapi-stream:s34767?sid=254&amp;amp;flags=32&lt;/res&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</Result>
      <NumberReturned>1</NumberReturned>
      <TotalMatches>1</TotalMatches>
      <UpdateID>1</UpdateID>
    </u:BrowseResponse>
  </s:Body>
</s:Envelope>
```

The contents of `Result` are encoded. Once decoded, you get back more XML, which is easy enough to parse:

``` xml
<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
  <item id="R:0/0/0" parentID="R:0/0" restricted="false">
    <dc:title>105.9 | Power 106 (Hip Hop)</dc:title>
    <upnp:class>object.item.audioItem.audioBroadcast</upnp:class>
    <res protocolInfo="x-rincon-mp3radio:*:*:*">x-sonosapi-stream:s34767?sid=254&amp;flags=32</res>
  </item>
</DIDL-Lite>
```

It's all straight-forward, so I should have the methods to get radio favorites added soon.

**Comment by avjui** [comment]
Nice thanks. I like to hear this.

Then I have a second request that based on this. 
Is it also possible to get radio logo instant ' '  in the function get_current_track_info()['album_art'] when sonos play a radio station.

**Comment by rahims** [comment]
I looked into getting the radio station's logo, but it isn't returned in the normal `GetPositionInfo` UPnP call, so the Sonos controller must be getting it some other way. (Most likely by querying TuneIn directly.)

I think it's best to open up a new, separate feature request thread in Github Issues for this so that I can track the information I find around it since this thread will be closed soon. (I'll be implementing the favorite radio list method today or tomorrow.)

**Comment by rahims** [comment]
Just pushed an update with two methods added: `get_favorite_radio_shows` and `get_favorite_radio_stations`:

``` python
get_favorite_radio_shows(start=0, max_items=100)
get_favorite_radio_stations(start=0, max_items=100)
```

Use them like this:

``` python
#!/usr/bin/env python
from soco import SoCo

if __name__ == '__main__':
    sonos = SoCo('10.0.0.102') # Pass in the IP of your Sonos speaker

    items = sonos.get_favorite_radio_stations()

    for favorite in items['favorites']:
        print favorite['title']
```

No support for returning the radio station's logo just yet, but I'll look into it.

These two methods have some extra information that make it easier to implement paging. In addition to the list of favorites, they also return the total number of favorites available in the system (`items['total']`). By checking to see if the total is greater that the number of items returned, you'll know if you need to page to get more favorites and can pass `start` and `max_items` arguments to the methods to do so.

**Comment by avjui** [comment]
Thanks
