### ISSUE TITLE
[Feature Request] Get event notifications (song change, pause, etc.)

### ISSUE THREAD

**Issue by rahims** [rahims/SoCo#14]
Requested by @labero through e-mail.

Would be very useful for those building GUI clients if they could get notifications when events occur, such as a song change.

**Comment by rahims** [comment]
I'll be working on implementing this over the next few days.

**Comment by labero** [comment]
Very interesting! I'll be keeping a close eye. :)

**Comment by rahims** [comment]
There's still work to be done, but I wanted to put up what I've got so far and get your feedback. I've pushed the initial bit of code for Sonos events to a new topic branch called "[sonos-events](https://github.com/rahims/SoCo/tree/sonos-events)".

The major difference is the addition of a new class `Events` contained in `events.py`. The new class depends on [gevent](http://www.gevent.org), so start by installing that:

`pip install gevent`

After that, use `Events` like this:

``` python
from soco import Events

s = None

def callback(data):
    print 'Got an event notification from the speaker: {0}'.format(data)

def ui_setup():
    s = Events('10.0.0.102') # Pass in the IP of your Sonos speaker
    s.subscribe(callback)
    s.start()
    # Rest of your one-time UI setup code

def ui_teardown():
    s.stop()
    # Rest of your UI teardown code
```

I haven't written parsing code yet, so for now you'll get the full, raw XML sent by the Sonos speaker. When an event occurs, it'll look something like this:

``` xml
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
  <e:property>
    <LastChange>
        <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/">
          <InstanceID val="0">
            <TransportState val="STOPPED"/>
            <CurrentPlayMode val="NORMAL"/>
            <CurrentCrossfadeMode val="0"/>
            <NumberOfTracks val="0"/>
            <CurrentTrack val="0"/>
            <CurrentSection val="0"/>
            <CurrentTrackURI val=""/>
            <CurrentTrackDuration val="0:00:00"/>
            <CurrentTrackMetaData val=""/>
            <r:NextTrackURI val=""/>
            <r:NextTrackMetaData val=""/>
            <r:EnqueuedTransportURI val=""/>
            <r:EnqueuedTransportURIMetaData val=""/>
            <PlaybackStorageMedium val="NONE"/>
            <AVTransportURI val=""/>
            <AVTransportURIMetaData val=""/>
            <CurrentTransportActions val="Set, Play, Stop, Pause, Seek, Next, Previous"/>
            <TransportStatus val="OK"/>
            <r:SleepTimerGeneration val="0"/>
            <r:AlarmRunning val="0"/>
            <r:SnoozeRunning val="0"/>
            <r:RestartPending val="0"/>
            <TransportPlaySpeed val="NOT_IMPLEMENTED"/>
            <CurrentMediaDuration val="NOT_IMPLEMENTED"/>
            <RecordStorageMedium val="NOT_IMPLEMENTED"/>
            <PossiblePlaybackStorageMedia val="NONE, NETWORK"/>
            <PossibleRecordStorageMedia val="NOT_IMPLEMENTED"/>
            <RecordMediumWriteStatus val="NOT_IMPLEMENTED"/>
            <CurrentRecordQualityMode val="NOT_IMPLEMENTED"/>
            <PossibleRecordQualityModes val="NOT_IMPLEMENTED"/>
            <NextAVTransportURI val="NOT_IMPLEMENTED"/>
            <NextAVTransportURIMetaData val="NOT_IMPLEMENTED"/>
          </InstanceID>
        </Event>
    </LastChange>
  </e:property>
</e:propertyset>
```

Here's one for a song playing:

``` xml
<?xml version="1.0"?>
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
  <e:property>
    <LastChange>
        <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/">
          <InstanceID val="0">
            <TransportState val="PLAYING"/>
            <CurrentPlayMode val="NORMAL"/>
            <CurrentCrossfadeMode val="0"/>
            <NumberOfTracks val="1"/>
            <CurrentTrack val="1"/>
            <CurrentSection val="0"/>
            <CurrentTrackURI val="x-sonos-http:track%3a65512991.mp3?sid=255&amp;flags=32"/>
            <CurrentTrackDuration val="0:02:37"/>
            <CurrentTrackMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt;&lt;res protocolInfo=&quot;sonos.com-http:*:audio/mpeg:*&quot; duration=&quot;0:02:37&quot;&gt;x-sonos-http:track%3a65512991.mp3?sid=255&amp;amp;flags=32&lt;/res&gt;&lt;r:streamContent&gt;&lt;/r:streamContent&gt;&lt;r:radioShowMd&gt;&lt;/r:radioShowMd&gt;&lt;upnp:albumArtURI&gt;/getaa?s=1&amp;amp;u=x-sonos-http%3atrack%253a65512991.mp3%3fsid%3d255%26flags%3d32&lt;/upnp:albumArtURI&gt;&lt;dc:title&gt;Crystal Castles - AFFECTION&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;dc:creator&gt;Crystal Castles&lt;/dc:creator&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/>
            <r:NextTrackURI val=""/>
            <r:NextTrackMetaData val=""/>
            <r:EnqueuedTransportURI val="x-sonos-http:track%3a65512991.mp3?sid=255&amp;flags=32"/>
            <r:EnqueuedTransportURIMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;10030020track%3a65512991&quot; parentID=&quot;100a0064favorites%3a27319611&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Crystal Castles - AFFECTION&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON65287_X_#Svc65287-0-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/>
          </InstanceID>
        </Event>
    </LastChange>
  </e:property>
</e:propertyset>
```

I'll likely parse that XML response into a structure and pass that back to subscribed listeners, but not sure what that structure will look like just yet. What's interesting is that the event information sent by the speaker is basically its entire state rather than a simple "I've begun playing a song" or "I skipped a song" message.

This is all still very early and rough (the method names are likely to change, maybe `start` will become `start_listening`? Not sure yet.), so I wouldn't put anything out in production with it yet, but please play around with it and give me your feedback. Is this sort of what you're looking for? What kind of functionality would you like to see?

I should add that right now it only subscribes to AVTransport events (play, pause, etc.), there are other endpoints on the speaker that can be subscribed to. For example the RenderingControl endpoint for notifications of changes in volume, treble, and bass. I'll add those as work progresses on this class.

**Comment by KennethNielsen** [comment]
This looks great. I will be interested in this as well. I actually couldn't figure out how to make it work with the code above :( I think it is a threading issue, could you throw me a hint, or perhaps an example.

With regards to the data structure of the return structure. With a lot of key/value pairs a dictionary seems like a good choice, however, I usually prefer wrapping the data in a class and then make the class work like a dictionary. That way it is possible to easily see what it is that you receive (say a EventContent object) and you can still call the return value as a dictionary for easy access. And what might be even more helpful is if there a different return class for each one of the endpoints that are tracked, so that it is possible to determine the type of event by testing the type of the return class.

**Comment by rahims** [comment]
Sorry, I just noticed `s.start()` shouldn't be called from inside a UI event loop since this would cause the server to start everytime the event loop is run through. Corrected my previous comment for future readers.

Here's a very contrived example of the new `Events` code running:

``` python
import gevent
from soco import Events

def callback(data):
    print 'Got data: {0}'.format(data)

if __name__ == '__main__':
    s = Events('192.168.1.80') # Replace with your Sonos' IP
    s.subscribe(callback)
    s.start()
    # Keep the program running for 60 seconds so that we have some time to
    # listen for notifications. Otherwise the program will run & exit right away.
    gevent.sleep(60)
    s.stop()
    print 'Shutting down'
```

While that's running, you can start up your Sonos controller and play a song to see the notifications it sends out.

**Comment by KennethNielsen** [comment]
Thanks I got it working now. Actually, it may have been just me staring my self blind on the last number in the IP address and the forgetting the second to last, sorry _hides embarrassed_.

**Comment by rahims** [comment]
One more example, this time with [Tkinter](http://wiki.python.org/moin/TkInter). I'm not actually familiar with Tkinter, so this is entirely from [this Github repo](https://github.com/rik0/Tk-Gevent-Example/blob/master/greenlet_for_dummies.py) with `Events` code tossed in.

``` python
import Tkinter as tk

import gevent
from soco import Events

class App:
    def __init__(self, root):
        self.event_server = None
        self.root = root
        self.__build_window(root)
        self.root.after(100, self.__start_listening)

    def add_text(self, text):
        self.text.insert(tk.END, "---New Event---\n")
        self.text.insert(tk.END, text + "\n")

    def __build_window(self, root):
        frame = tk.Frame(root)
        frame.pack()

        self.text = tk.Text(frame)
        self.text.pack()

        self.button = tk.Button(frame, text='Quit', command=self.quit)
        self.button.pack(side=tk.RIGHT)

    def quit(self):
        self.event_server.stop()
        self.root.quit()

    def __start_listening(self):
        self.event_server = Events('192.168.1.80')
        self.event_server.subscribe(self.add_text)
        self.event_server.start()
        self.gevent_loop_step()

    def gevent_loop_step(self):
        gevent.sleep()
        self.root.after_idle(self.gevent_loop_step)

root = tk.Tk()
app = App(root)
root.mainloop()
```

![Tkinter](https://f.cloud.github.com/assets/111628/142293/fa69ddda-72dc-11e2-8fbc-69c197e02af3.png)

**Warning**: this works nicely until you try to quit the application. When you do that, it freezes (again, I know nothing about Tkinter). Perhaps, @labero will be able to give some insight.

**Comment by labero** [comment]
Looks very interesting. I've look at the code and made some small structural changes. However, since I'm not at home I haven't been able to test if my changes actually works.

This is also the first time I've worked with gevent, so I'll dig into it when I can do some tests. Hopefully I'll find some time this evening.

**Comment by labero** [comment]
Hello again,

I've been thinking about the events and how it could be implemented. How about this:

The goal with this idea is to make the library as simple as possible. I believe that for the end user something similar to the code below would be as simple as possible:

<pre>
>>> speaker = SoCo('192.168.1.123')
>>> print speaker.get_current_track_info()
>>> def print_track_change(params):
    print 'Got an event'
>>> speaker.subscribe(  print_track_change, 
                    event_type = 'TRACK_CHANGE')
.
.
.
>>> speaker.unsubscribe(    print_track_change,
                    event_type = 'TRACK_CHANGE')
</pre>

It's not very hard to make changes to the current code base in order to achieve this. Firstly, SoCo just needs to inherit from Event. Then I think that it would be really nice to hide the server parts (start and stop methods). 

The idea is to start the server in its own thread when the first subscription is made. The event server should off course be stopped when SoCo gets the last unsubscribe. In general I believe that most of the users would not care from which thread the events are coming from. It gets a little bit tricker working with GUIs. I only have GUI-experience with Java Swing/SWT, but it is doable there so I don't see why it wouldn't work with python.

I've started working with subscribe/unsubscribe methods but I haven't tested it yet.

**Comment by KennethNielsen** [comment]
I like the idea of interfacing the events code though wrapper methods in the SoCo class. That will give access to the IP-address once the soco class is instantiated and will present a single interface for the controller. However, I would propose to still keep the events code in a separate class and file for modularization purposes, to make sure that the soco class does not explode in size and complexity.

**Comment by labero** [comment]
I totally agree. That was what i had in mind, apparently I managed to
describe it sloppy. :)

**Comment by rahims** [comment]
Thanks, guys. Bringing it into SoCo itself makes sense, and I agree about the ability to subscribe to specific events, like "track change".

I'll look more into threading vs gevent. I'm new to gevent as well, but it looks like a good solution, since it's so easy to write from a library perspective (the source is easy to read and understand) and has a nice WSGI server. In the end, how easy it is for developers to use the library to make cool things is more important to me than the library's technologies underneath, so I've got no problem ditching gevent. I'll look more into hiding gevent better so that a person using the library never even knows it's there (`gevent.sleep` in one's code is off-putting) and also write up a separate Events class that uses threading so that we can compare.

**Comment by KennethNielsen** [comment]
I guess gevent uses threads in some way or another, otherwise I don't think it would be possible to call the subscribe and have the call return to the caller. Personally I think that if there is a library available that makes the implementation easy by doing some of the legwork and if that lib is easily available (gevent _is_ in package libraries on Linux) then I'm all for ;) No need to write everything from scratch unless the needs arises.

**Comment by labero** [comment]
I've tried to make events threaded, but it wasn't easy with gevent. I don't have a solution yet, but I have to give up for today I am way to tired now. :)

**Comment by scottgwaters** [comment]
Great to see this being worked on. I have a use for this. Trying to setup a raspberry pi to sense when a sonos connect is playing and turn an amp on or off. Have your module up and running great. Thanks for all the work. hopefully I can contribute even if its jus testing.

**Comment by scottgwaters** [comment]
get this error when trying to install module

gevent/libevent.h:9:19: fatal error: event.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by scottgwaters** [comment]
Ok I didn't have all dependencies installed.

sudo apt-get install libevent-dev
sudo pip install greenlet
sudo pip install gevent

**Comment by KennethNielsen** [comment]
@scottgwaters If you are on Ubuntu (and likely also Debian) gevent (along with requests) is also available directly from the package archive as "python-gevent". That should take care of the dependencies automatically.

**Comment by scottgwaters** [comment]
@kennethNielsen thanks. I'm on Debian. I am now getting a different error. I've gone ahead and installed dependencies with 

sudo apt-get install python-gevent

Traceback (most recent call last):
  File "feedback.py", line 2, in <module>
    from soco import Events
  File "/usr/local/lib/python2.7/dist-packages/soco-0.4-py2.7.egg/soco.py", line 18, in <module>
    from events import Events
ImportError: No module named events

**Comment by rahims** [comment]
@scottgwaters Could you check to make sure you pulled down the SoCo source code from the "[sonos-events](https://github.com/rahims/SoCo/tree/sonos-events)" branch rather than the "[master](https://github.com/rahims/SoCo)" branch? The Events code is still very much alpha, so it's being developed in a separate branch.

**Comment by rahims** [comment]
@labero Thanks for trying! I'm going to be busy for about a week (need to do a last minute move to a new apartment), so I won't be able to take a crack at it as soon as I'd like to, but will be on it as soon as I can.

**Comment by scottgwaters** [comment]
@rahims I had previously installed master. Maybe that is the problem. I've actually forked master and added a command to see if the speaker is playing or stopped.

**Comment by DrSAR** [comment]
This looked very promising. I am very interested to follow up with this. What is the latest thinking on integrating listening to events with SoCo? Has this been abandoned due to a competing solutions or is it still worth pursuing?

**Comment by stefankoegl** [comment]
In my opinion its definitely still worth pursuing. A lot of internals have changed since, and the main repository has been moved to [SoCo/SoCo](https://github.com/SoCo/SoCo), so you'll find the latest code there.

If you start working on this, you could restart the discussion there to have everything centralized.

**Comment by DPH** [comment]
+1 would love to see this progressed - under SoCo/CoCo

**Comment by KennethNielsen** [comment]
Me too. As far as a remember, most of the code is already there to get the events, what was missing was a way to make them available. I think @rahims was considering what mechanisms to use like maybe a kind of signals, but I would actually suggest that, just to begin with and to make sure that there is a simple solution too, to implement a solution with a queue first, then something with singnals can always come later if the need arises.

However, the others are right, this work should continue under SoCo/SoCo.

**Comment by DrSAR** [comment]
Thanks for the input. Issuw now moved to https://github.com/SoCo/SoCo/issues/86
I guess this can be closed.
