### ISSUE TITLE
[Feature proposal] Unit tests

### ISSUE THREAD

**Issue by KennethNielsen** [rahims/SoCo#16]
First of, thank to rahims for creating the project and to everyone else who has contributed. It looks to be a promising project.

Since there seem to be a great deal of development activity, I thought it would be helpfull with some unit tests of the soco methods, to watch out for regressions.

I'm already working on it and I'm posting mostly to avoid double work. If anyone else is working on something like this, please let me know.

**Comment by rahims** [comment]
Unit tests would be very helpful--thanks! :thumbsup: (I'm not working on any currently.)

**Comment by KennethNielsen** [comment]
I have made a pull request for the first few unittests, but I suggest that we keep this issue open until the unit test coverage is more complete.

**Comment by rahims** [comment]
Cleaning up by closing this issue since we can discuss it in #17.

**Comment by KennethNielsen** [comment]
Makes sense. Thanks.
