### ISSUE TITLE
[BUG] Encode Error with 'get_favorite_radio_stations'

### ISSUE THREAD

**Issue by avjui** [rahims/SoCo#20]
Here is the Traceback

``` javascript
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    items = sonos.get_favorite_radio_stations(start=0, max_items=9)
  File "/mnt/Media/Downloads/Homematic/lib/sonos/soco.py", line 840, in get_favorite_radio_stations
    return self.__get_radio_favorites(RADIO_STATIONS, start, max_items)
  File "/mnt/Media/Downloads/Homematic/lib/sonos/soco.py", line 858, in __get_radio_favorites
    dom = XML.fromstring(response)
  File "<string>", line 106, in XML
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 3372: ordinal not in range(128)
```

This error come by parsing the name 'Ö2 Radio'

**Comment by KennethNielsen** [comment]
@avjui I think that was one of the errors that I addressed with a pull request from yesterday (https://github.com/rahims/SoCo/blob/master/soco.py#L859). Could you try and fetch the latest master and see if the error still occurs. If it does please let me know where in the browse radio stations I can find this station.

**Comment by avjui** [comment]
It seem your are right so we close this. Thanks
