### ISSUE TITLE
[Discussion] Form IRC channel for soco

### ISSUE THREAD

**Issue by KennethNielsen** [rahims/SoCo#31]
Hallo

I was wondering whether anyone else would be interested in an IRC channel for soco. I think that every once in a while, there are some things that could be better solved via IRC. There should of course be no obligation to how much time people use on the channel, but just whenever we feel like it.

What do you think?

**Comment by DPH** [comment]
Like the idea of interaction to solve some issues but never used IRC. Would Google groups provide the needed facilities?

Big issue will be time zone and people's availability. Supportive if others are interested.

This is a great project and has so many opportunities. I am using it more and more with my Sonos, and running the code on a Raspberry Pi.

Cheers Daivd

**Comment by stefankoegl** [comment]
+1 for IRC

**Comment by rahims** [comment]
I'd be fine with either. Though, I don't know how often I could be in the IRC channel because my schedule is kind of all over the place. Looking forward to sitting down later today with all the awesome updates you guys have been making these past two weeks though! :smile:

**Comment by KennethNielsen** [comment]
@DPH I was actually looking for something that would give us an opportunity to interact real-time. As far as I can tell Google groups only have that in the form of group chats that needs to be manually initiated. With IRC we will just have a chat channel open 24-7 that we can log into whenever we want to.

Given the feedback here, I wen't ahead and created the channel. Then we will see if it turns out to be useful. The channel is named #soco and is located on the freenode network.

@rahims Will you add it to the project front page?

**Comment by rahims** [comment]
Not a problem, updated the readme (which automatically renders as the front page). In the channel as well.

**Comment by KennethNielsen** [comment]
There is now also a reference back to the project webpage in the topic for the channel, closing this thread.
