### ISSUE TITLE
[Proposal] Move soco to a group project

### ISSUE THREAD

**Issue by KennethNielsen** [rahims/SoCo#34]
Hi everyone

Lately there has been quite a lot of interest in the development of SoCo and therefore I am opening this discussion about moving the development to a group project. The advantages as I see them are:
- This will serve as an easily identifiable "official" repo 
- It will make for a more suitable location for documentation, if we start writing some in the wiki (which is what officially prompted me to make the suggestion)
- It will make the development more scalable and flexible

Just to make sure that this doesn't come of in the wrong way (internet communication can be tricky sometimes). This suggestion is **not** about lobbying for more influence or commit rights to the "official" repo or anything like that. The project was formed by @rahims and I think he has done a completely awesome job of founding and maintaining it ;) so if we were to make this change it could perfectly well be made with @rahims as the only member of the group to make for a situation equivalent to the one we have today. But the point about it being flexible is that it _will_ then be possible e.g. to delegate during real life busy periods.

Best Regards Kenneth

**Comment by stefankoegl** [comment]
+1

One note to documentation: I've been working on integrating SoCo with https://readthedocs.org/ lately. I hope I have a first pull-request in a few days

**Comment by rahims** [comment]
I think that's a good idea. I'll set up the group  this weekend.

**Comment by rahims** [comment]
So, "SoCo" is already taken (http://github.com/soco). It looks like the account was created a few years ago and hasn't been used, so maybe the folks at Github will allow us to reclaim the name. (Similar to how Twitter does it with inactive accounts.) Or, we could rename the project to something else, though that might hurt discovery a bit since the existing name already has a year's worth of search juice. Alternatively, I did some exploring, and it looks like I can add collaborators to the existing project which would allow you guys to have admin rights over the repo. Thoughts?

**Comment by DPH** [comment]
Agree to keep the name. As interest builds a name change can loose the
momentum.
See if Github allows reclaim - or approach the owners directly (although
can't see how to find them)?
I am still learning about Github.

If not then is adding collaborators achieves the same go for that.

Great work
Cheers Daivd

**Comment by stefankoegl** [comment]
An organization makes most sense if you want to host multiple repositories under one "project name". I'd recommend trying to reclaim the name, and adding team members to the existing repository as an intermediate solution (if required).

**Comment by DPH** [comment]
Well done - shows the power of networks.

I assume we need some "guidelines" on using it: eg always have at least 2
people approve code
There must be some principals out there for other group projects.

Cheers Daivd

**Comment by KennethNielsen** [comment]
@DPH Yeah, that sounds like a good idea. I would probably make them a little less restrictive to begin with, to not make it to troublesome to contribute, something like 1 approval and no-one wildly objecting with in a week. But maybe we should open a separate issue to discuss that once the transition has happened.

**Comment by rahims** [comment]
Spoke to a friend at Github and he was able to reclaim the name for us, https://github.com/soco. I've copied over the current repo to the new organization, set up the initial team [1] and given them push/pull and full admin rights. Going forward, please fork, star, and send pull requests to the newly official repo: https://github.com/SoCo/SoCo.

The issues and existing pull requests didn't transfer over, but I hope that's not too much of a problem. Doing an outright transfer of the repo would have broken all the forks, so I figured it was best to do a more gradual transition with new work going to the new repo. I've added a notice on the home page as well.

[1] The admin team is initially set up to be me, @KennethNielsen, and @stefankoegl. Both Kenneth and Stefan have been contributing to the project for some time now and always have good ideas and friendly feedback. I'm not opposed to adding more members, but I figured this was a good starting team.

**Comment by stefankoegl** [comment]
I've updated the settings on Read The Docs (#36) to reflect the move. 

On a related note, I'd have preferred a full move (including tickets, etc) and deliberately breaking users clones, so they know that they have to update.

**Comment by KennethNielsen** [comment]
This seems mostly done. Let's discuss any future issues related to the move on the new location and close this issue.

**Comment by stefankoegl** [comment]
As user TLE in #soco asked how to migrate a local clone to the moved repository:

```
git remote set-url origin git@github.com:SoCo/SoCo.git
```
