### ISSUE TITLE
Release Procedure

### ISSUE THREAD

**Issue by stefankoegl** [rahims/SoCo#39]
I've packaged SoCo for PyPI some time ago (http://pypi.python.org/pypi/soco). The published version is, however, still 0.1 and thus quite outdated, as we seem to be at 0.5 right now. I'll update the package soon, but I'd like to propose and discuss the workflow first.

I assume that the job of versioning will be done by @rahims, right? If so, I'd like to agree on some procedure for that. My suggestion:
1. bump the version in soco.py
2. create an [annotated tag for the new version](http://git-scm.com/book/en/Git-Basics-Tagging#Annotated-Tags)
3. Some some about the new version via some channel (irc? #31)
4. I package and publish the new version

Having a tag for each version makes it very easy to use GitHub's [compare view](https://github.com/blog/612-introducing-github-compare-view) to create a simple change log (commit range between current and previous tag).

I'd be very happy about some feedback!

**Comment by KennethNielsen** [comment]
I think that sounds good.

I was wondering by the way, how people usually use sphinx when they do documentation. Maybe stuff like this, programming conventions, design discussion etc., and other more lively information will go better on the wiki and the sphinx docs is reserved for programming documentation, tutorial and code examples etc?

What do you think.

\Regards Kenneth

**Comment by stefankoegl** [comment]
That might be a bit OT, but GitHub lets you put [Contributing Guidelines](https://github.com/blog/1184-contributing-guidelines) in a specific file that is then shown when creating the pull request. So this would be the ideal place to summarize / link to coding standards, etc. Putting architecture related information into Sphinx docs or the wiki should be ok, but probably we should discuss that separately.

**Comment by KennethNielsen** [comment]
Ahh the contributing file looks like the ideal place.

Yes, lets take that in another thread. I guess my thought was that the docs should be just the docs, so that e.g. if people wanted to keep a more lively TODO or try to draft something that is probably more suited for wiki. Oh well, just thoughts.

**Comment by KennethNielsen** [comment]
Development of SoCo contionues under https://github.com/SoCo
