### ISSUE TITLE
[POLL] What music services do you use.

### ISSUE THREAD

**Issue by scottgwaters** [rahims/SoCo#40]
I would be interested in knowing what music services people are using that way if there are a few shared services I can work on those first. Here is what I use

Pandora
Spotify
Slacker

**Comment by stefankoegl** [comment]
Spotify

**Comment by KennethNielsen** [comment]
Wimp. Not sure if it is specific to Denmark. I was close to subscribing to Spotify and may shift if I can't figure wimp out.

**Comment by rahims** [comment]
In order of use:
- Pandora
- Rdio
- iHeartRadio

**Comment by petteraas** [comment]
I use Wimp here in Norway, I believe it's only available in a few European countries.

**Comment by phut** [comment]
Tunein - I happened to use it pre-sonos then found out that it is the framework behind the radio stations on sonos anyway (at least it is in the uk)
spotify

**Comment by DPH** [comment]
Use a lot:
- Napster (UK version of Rhapsody) - think it works the same just branding
- Radio (via Tune In I think) - although BBC Radio 6 Music seems to behave differently

occasionally use:
- Last FM (but always Scroble to it - great service - track all the music you play and provides stats)
- Audpeo

would like to use:
- Google Music (but not supported yet - if ever)
- Amazon MP3 & Cloud Music (but not supported in UK - only US for now!)

**Comment by KennethNielsen** [comment]
Since we are moving, we should see if we can close all the old issues. I'm assuming that you have enough information and will close the issue. Feel free to reopen if you still need more feedback.
