### ISSUE TITLE
Source code here does not match published SoCo

### ISSUE THREAD

**Issue by anonfunc** [rahims/SoCo#43]
https://pypi.python.org/pypi/soco/0.6

SoCo there points here, but the version there is 0.6 and the source layout is different.
Is SoCo's source still hosted here?

I'm planning on using SoCo for https://github.com/anonfunc/remote/

**Comment by DPH** [comment]
This has been migrated to ScCo/SoCo - I follw, use and contribute a little.
Lots of additions here
Cheers David

**Comment by anonfunc** [comment]
Okay, so the only issue here is the description at pypi.
Thanks!

**Comment by KennethNielsen** [comment]
It seems that @stefankoegl has updated the description at pypi. Thanks for the bug report.

**Comment by stefankoegl** [comment]
I've fixed that in SoCo/SoCo@23ed9157fa1aeea9887f4e20f1d612e28b2db6b9
