### ISSUE TITLE
Question about Queue

### ISSUE THREAD

**Issue by Reborn2** [rahims/SoCo#47]
Hello

Using Soso and have a question about commands.

SonosSoCo.get_current_track_info() lets report the informations of the current track where i can read the informations like artist album title thats all okay

SonosSoCo.get_queue() lets report the playlist as queue but i cant pick out the information about the next track

Is there an command for getting just the information of the next track

Regards

**Comment by KennethNielsen** [comment]
Hi @Reborn2 

All development of SoCo has moved to https://github.com/SoCo/SoCo. Please re-postyour question there. We also have a google group and an IRC channel which are the preferred media for support.
